source 'http://rubygems.org'

# Core Rails version
gem 'rails', '3.0.9'

# generator helper gem
gem 'rails3-generators'

#javascript related
gem 'therubyracer'
gem 'barista'
gem 'jquery-rails'

# rails server
gem 'thin'

#DB Protocol
gem 'mysql2', '0.2.6'

#Basic search help engine
gem 'meta_where'

#Full Text searching engine
gem 'sunspot'


# HTML Parsing tools
#gem 'yajl-ruby', :require => 'yajl'
#gem 'nokogiri'

# Paginator
#gem "kaminari"


# File Uploads
# gem 'paperclip'


# Authentication
#gem 'devise'

# Authorization
#gem "cancan"

# Form Helpers
gem "simple_form"

# Replaces ERB
gem "haml"
gem "haml-rails"

# SASS
gem 'sass'

# Deploy with Capistrano
# gem 'capistrano'


group :test, :development do
  gem 'ruby-debug19', :require => 'ruby-debug'
  gem 'w3c_validators'
  gem 'cucumber'
  gem 'cucumber-rails'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'rb-inotify'
  gem 'guard-rspec'
  gem 'guard-cucumber'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'pickle'
  gem 'factory_girl_rails'
  gem 'launchy'
  gem 'escape_utils'
end

